dist: trusty
sudo: required
language: cpp
fast_finish: true



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
      - gfortran

compiler: gcc
env: GCC_VERSION=7
  - CC=gcc-7
  - CXX=g++-7
  - FC=gfortran
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran"


notifications:
  email: false

cache:
  apt: true


before_install:
    - eval "${MATRIX_EVAL}"

script:
  - export CXX="g++-7" CC="gcc-7" FC="gfortran"
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


