dist: trusty
sudo: required
language: cpp
fast_finish: true
notifications:
  email: false



matrix:
  include:
  - os: linux
    compiler: gcc
    env: GCC_VERSION=7
      - CC=gcc-7
      - CXX=g++-7
      - FC=gfortran
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran"
    cache:
      apt: true
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-7
          - gfortran
    before_install:
      - eval "${MATRIX_EVAL}"

  - os: linux
    compiler: clang
    env: CLANG_VERSION=5.0 LIBCXX=On
      - CC=clang-5.0
      - CXX=clang++-5.0
      - FC=gfortran
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran"
    cache:
      apt: true
    addons:
      apt:
        sources:
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        packages:
          - clang-5.0
          - llvm-5.0-dev
          - gfortran
    before_install:
      - eval "${MATRIX_EVAL}"



script:
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


