dist: trusty
sudo: required
language: cpp
fast_finish: true



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
      - gfortran-7
      - clang-5.0
      - cmake

compiler: gcc
env: GCC_VERSION=7
  - CC=gcc-7
  - CXX=g++-7
  - FC=gfortran-7

notifications:
  email: false

cache:
  apt: true




script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7" FC="gfortran-7"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0" FC="gfortran-7"; fi
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


