dist: trusty
sudo: false
language: cpp
notifications:
  email: false



matrix:
  fast_finish: true
  include:
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc GCC_VERSION=7 CC=gcc-7 CXX=g++-7 FC=gfortran
    cache:
      apt: true
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-7
          - gfortran

  - os: linux
    compiler: clang
    env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0 CLANG_VERSION=5.0 FC=gfortran
    cache:
      apt: true
    addons:
      apt:
        sources:
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
          key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
          - llvm-5.0-dev
          - clang-5.0
          - gfortran



script:
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


