dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
      - gfortran-7
      - cmake


cache:
  apt: true
script:
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


