dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

cache:
  apt: true
script:
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


