dist: trusty
sudo: true
language: cpp
fast_finish: true



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
      - gfortran-7
      - clang
      - cmake

notifications:
  email: false

cache:
  apt: true

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 FC=/usr/bin/gfortran-7
  - cmake -E make_directory build/Release
  - cd build/Release
  - cmake -Bbuild/Release --build build -config Release ../../
  - make


