dist: trusty
sudo: false
language: generic
notifications:
  email: false
branches:
  only:
    - master


matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc-7
      env:
        - COMPILER_NAME=gcc
        - GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
        - FC=gfortran-7
        - MPI=mpich
        - MATRIX_EVAL="CXX=g++-7 && CC=gcc-7 && FC=gfortran-7 && MPI=mpich"
      cache:
        apt: true
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-7
            - g++-7
            - gfortran-7
            - mpich 
            - libmpich-dev
    - os: linux
      compiler: clang
      env:
        - COMPILER_NAME=clang
        - CXX=clang++-6.0
        - CC=clang-6.0
        - CLANG_VERSION=6.0
        - FC=gfortran-7
        - MPI=mpich
        - MATRIX_EVAL="CXX=clang++-6.0 && CC=clang-6.0 && FC=gfortran-7 && MPI=mpich"
      cache:
        apt: true
      addons:
        apt:
          update: true
          sources:
          - sourceline:  'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-6.0-dev
            - clang-6.0
            - libstdc++-7-dev
            - gfortran-7
            - mpich 
            - libmpich-dev
    - os: linux
      compiler: gcc-7 (preinstalled libs)
      env:
        - COMPILER_NAME=gcc
        - GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
        - FC=gfortran-7
        - MPI=mpich
        - MATRIX_EVAL="CXX=g++-7 && CC=gcc-7 && FC=gfortran-7 && MPI=mpich"        
      cache:
        apt: true
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-7
            - g++-7
            - gfortran-7
            - libhdf5-dev
            - libhdf5-serial-dev
            - hdf5-helpers
            - hdf5-tools
            - libgsl0-dev
            - libopenblas-dev
            - libarpack2-dev
            - libarpack++2-dev
            - mpich 
            - libmpich-dev
    - os: osx
      osx_image: xcode9.1 #Newer versions don't like experimental/filesystem or _stdio.h?
      compiler: gcc-7
      env:
        - COMPILER_NAME=gcc
        - GCC_VERSION=7
        - CXX=g++-7
        - CC=gcc-7
        - FC=gfortran-7
        - MPI=mpich
        - MATRIX_EVAL="CXX=g++-7 && CC=gcc-7 && FC=gfortran-7 && MPI=mpich"      
      before_install:
        - brew cask uninstall oclint
        - brew install gcc@7
        - brew install openmpi

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./build.sh -m Debug -j2


