from matplotlib.ticker import LogLocator, \
    LogFormatter, LogFormatterExponent, LogFormatterSciNotation, \
    LogFormatterMathtext, NullFormatter, MultipleLocator, MaxNLocator, \
    FixedLocator, LinearLocator, ScalarFormatter
import numpy as np
from pathlib import Path

mplstyle = '../common/stylesheets/prb.mplstyle'
# mplstyle = '../common/stylesheets/slack.mplstyle'
prb = 'prb' in mplstyle



def get_meta(plotdir):

    default = {
        'box_aspect': 1,
        'subspec_title': False,
        'figspec_title': False,
        'legendoutside' : False,
        'legendcollect' : False
    }
    tallplot = {
        'box_aspect': 2.0,
        'subspec_title': False,
        'figspec_title': False,
        'legendoutside' : False,
        'legendcollect' : False
    }
    figsize1x1_fullcol = 3.404*0.55, 3.404, # Half-size compared to 2x1, plus some extra
    figsize1x1_halfcol = 3.404*0.50, 3.404, # Half-size compared to 2x1, plus some extra
    subplots1x1={
        'top': 1.0,
        'bottom': 0,
        'left': 0.22,
        'right': 0.99,
    }

    figsize2x1 = 3.404, 3.404,
    subplots2x1={
        'top': 1.0,
        'bottom': 0,
        'left': 0.13,
        'right': 0.99,
    }
    figsize2x2 = 3.404, 3.404,
    subplots2x2={
        'top': 0.96,
        'bottom': 0.09,
        'left': 0.12,
        'right': 0.99,
        'wspace':0.00,
        'hspace':0.00,
    }
    figsize3x1 = 6.808,3,404,
    subplots3x1={
        'top': 1.0,
        'bottom': 0,
        'left': 0.11,
        'right': 0.99,
    }
    meta = {
        'common': {
            'include': {
                # 'L': ['L_32'],
                # 'L': ['L_8', 'L_12', 'L_16', 'L_20'],
                # 'L': ['L_12'],
                # 'x': ['x_0.5000', 'x_1.0000'],
                # 'f': ['f_0.0125', 'f_0.0250', 'f_0.0500','f_0.0750'],
                # 'f': ['f_0.1000', 'f_0.1250', 'f_0.1500','f_0.1750','f_0.2000'],
                # 'f': ['f_0.5000'],
                # 'f': ['f_0.1500', 'f_0.2500', 'f_0.3000'],
                # 'f': ['f_0.4000', 'f_0.5000', 'f_0.6000'],
                # 'f': ['f_0.5000', 'f_1.0000', 'f_2.0000', 'f_3.0000', 'f_4.0000', 'f_5.0000'],
                # 'u': ['u_2', 'u_3'],
                # 'f': ['f_0.4500'],
                # 'u': ['u_5', 'u_6'],
                # 'u': ['u_5'],
                # 'w': ['w[+1.0000_+0.2500_+0.1000]', 'w[+1.0000_+0.5000_+0.1000]']
            },
            'include_v3': {
                # 'L': [36],
                # 'L': [12],
                # 'L': ['L_8', 'L_12', 'L_16', 'L_20'],
                # 'L': [24],
                # 'x': ['x_0.5000', 'x_1.0000'],
                # 'f': ['f_0.0125', 'f_0.0250', 'f_0.0500','f_0.0750'],
                # 'f': ['f_0.1000', 'f_0.1250', 'f_0.1500','f_0.1750','f_0.2000'],
                # 'f': [0.4],
                'f': [0.2, 0.4],
                #'f': [0.2, 0.3, 0.4],
                'L': [12,16,20,24,28,32],
                # 'L': [16,24],
                # 'L': [20],
                # 'f': ['f_0.1500', 'f_0.2500', 'f_0.3000'],
                # 'f': ['f_0.4000', 'f_0.5000', 'f_0.6000'],
                # 'f': ['f_0.5000', 'f_1.0000', 'f_2.0000', 'f_3.0000', 'f_4.0000', 'f_5.0000'],
                # 'u': ['u_2', 'u_3'],
                # 'f': ['f_0.4500'],
                # 'u': ['u_5', 'u_6'],
                # 'u': [32],
                # 'w': ['w[+1.0000_+0.2500_+0.1000]', 'w[+1.0000_+0.5000_+0.1000]']
                # 'tgw8': ['ID'],
                # 'cgw8': ['EX'],
                # 'u': [8,16,24,32,40,48,56,64],
                # 'u': [8, 16, 32, 64, 80],
                # 'ubond': [256],
            },
        },

        'ent': {
            'default' : default,
            'constrained_layout' : False,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'entanglement_entropy',
            'normpage': False,
            'normsinf': False,
            #'titlename': 'Entanglement Entropy',
            'ylabel': '$\overline S_\mathrm{E}$',
            'xlabel': '$t$',
            'xticks': [1e0, 1e3, 1e6, 1e9, 1e12],
            #'xmin': 1e-2,
            #'xmax': 5e+13,
            # 'ymax': 2.49,
            # 'yscale': 'log',
            'yformat': '%.2f',
            'xmaloc': LogLocator(base=10, numticks=5, numdecs=5),
            # 'xmiloc': LogLocator(base=10, numticks=10, subs=(.1, .2, .3, .4, .5, .6, .7, .8, .9)),
            # 'ymax': 2.38, # To make room for an axes label with a box
            'xmafmt': LogFormatterMathtext(labelOnlyBase=False),
            'plotprefix': 'SE',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marklogwindow': True,
            'marksaturation': True,
            'findloglogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset' : 0.1,
            'fillerror': True,
            'timeselection': 'lnt',
            'timenormalization': '',
            'mplstyle': mplstyle,
            'legendcols': ['L','num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'f','num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            # 'legendlocation': [ (0.75, 0.42), (0.75, 0.42), (0.75, 0.42), (0.75, 0.42), ],
            'legendlocation': [ 'upper right', 'upper right', 'upper right','upper right', ],
            'bbox_to_anchor': (1.05, 1.05), # Use with loc 'upper right'
        },
        'enta-lnt': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'entanglement_entropy',
            'normpage': False,
            'normsinf': False,
            'filter': {
                'L': [16, 20, 24, 28, 32],
            },
            # 'titlename': 'Number Entropy Approach to saturation',
            'ylabel': '$|\overline S_\mathrm{E}^\infty - \overline S_\mathrm{E}|$',
            'xlabel': '$t$',
            # 'yformat': '%.2f',
            # 'yscale': 'log',
            # 'xticks': [1e0,1e2,1e4],
            # 'xmaloc': LogLocator(base=10, numticks=5, numdecs=7),
            # 'xmafmt': LogFormatterMathtext(labelOnlyBase=True),
            # 'ymin': 1e-6,
            # 'ymax': 5e-2,
            # 'xmin': 1e-6,
            # 'xmax': 1e1,
            'plotprefix': 'SEA',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'markloglogwindow': False,
            'fitloglogwindow': False,
            'plotsatapproach': True,
            'plotsatapproachfits': False,
            'usescatterplot': False,
            'fillerror': False,
            'marksatapproach': True,
            'timeselection': 'lnt',
            'timenormalization': '',
            'mplstyle': mplstyle,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'

            # 'legendlocation': (0.55, 0.44),
            'legendlocation': 'upper right',
            'bbox_to_anchor': (1.05, 1.05),
        },
        'varN': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline \Delta N ^2$',
            'xlabel': '$\ln \ln t$',
            'yformat': '%.2f',
            'sharex': 'all',
            'sharey': 'none',
            'xticks': [-1, 0, 1, 2, 3],
            'ytickparams': {
                'axis': 'y',
                'direction': 'in',
                'pad': -22,
            },

            'ylabel_inner_visible': False,
            # 'ymin': 0.31,
            # 'ymax': 0.36,
            'xmin': -1.5,
            'xmax': 3.6,
            # 'yscale': 'log',
            'plotprefix': 'VarN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'plotVarN' : True,
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num1': {
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N}$',
            'xlabel': '$t$',
            'yformat': '%.2f',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num-lnt-norm': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'normsinf': True,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N} / S_\mathrm{N}^\infty$',
            'xlabel': '$\ln t  / (S_\mathrm{E}^\infty / S_\mathrm{Page})$',
            'sharex': 'None',
            'yformat': '%.3f',
            # 'yscale': 'log',
            # 'xscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': False,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            # 'timeselection': 't',,
            'timeselection': 'lnt',  # Choose t, lnt, lnlnt or SE
            'timenormalization': '/SEinfty*Spage',  # Choose (/*) SEinfty or Spage
            # 'timenormalization' : '*SEinfty/Spage', # Choose (/*) SEinfty or Spage
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num-se-norm': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'normsinf': True,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N} / S_\mathrm{N}^\infty$',
            'xlabel': '$\overline S_\mathrm{E} / (S_\mathrm{E}^\infty / S_\mathrm{Page})$',
            'sharex': 'None',
            'yformat': '%.3f',
            # 'yscale': 'log',
            # 'xscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': False,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            # 'timeselection': 't',,
            'timeselection': "SE",  # Choose t, lnt, lnlnt or SE
            'timenormalization': '/SEinfty*Spage',  # Choose (/*) SEinfty or Spage
            # 'timenormalization' : '*SEinfty/Spage', # Choose (/*) SEinfty or Spage
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num-lnlnt-norm': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'normsinf': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N} / S_\mathrm{N}^\infty$',
            'xlabel': '$\ln\ln t / (S_\mathrm{E}^\infty / S_\mathrm{Page})$',
            'sharey': 'None',
            'sharex': 'all',
            'yformat': '%.3f',
            # 'yscale': 'log',
            # 'xscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': False,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            # 'timeselection': 't',,
            'timeselection': 'lnlnt',  # Choose t, lnt, lnlnt or SE
            'timenormalization': '/SEinfty*Spage',  # Choose (/*) SEinfty or Spage
            # 'timenormalization' : '*SEinfty/Spage', # Choose (/*) SEinfty or Spage
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num1-med': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\\tilde S_\mathrm{N}$',
            'xlabel': '$t$',
            'yformat': '%.3f',
            'ystat': 'med',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': False,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num1-typ': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\\tilde S_\mathrm{N}$',
            'xlabel': '$t$',
            'yformat': '%.3f',
            'ystat': 'typ',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': False,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num2': {
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter':{
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'ylabel': '$\overline S_\mathrm{N}$',
            'xlabel': '$\ln\ln t$',
            'yformat': '%.2f',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            'xticks': [-1,0,1,2,3],
            'ytickparams': {
                'axis' : 'y',
                'direction': 'in',
                'pad' : -22,
            },

            'ylabel_inner_visible': False,
            # 'ymin': 0.31,
            # 'ymax': 0.36,
            'xmin': -1.5,
            'xmax': 3.6,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marklogwindow': True,
            'marksaturation': True,
            'findloglogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.008,
            'fitloglogwindow': False,
            'fillerror': False,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': ['upper left','center right','upper left','center right'],
            'bbox_to_anchor': [(-0.05, 1.05),(1.05, 0.55),(-0.05, 1.05),(1.05, 0.55)],  # Use with loc 'upper right'

        },
        'num2-med': {
            'default': default,
            'axtitle': False,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'xlabel': '$\ln\ln t$',
            'ylabel': '$\overline S_\mathrm{N,median}$',
            'yformat': '%.3f',
            'ystat' : 'med',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 0.0,
            # 'xmax': 2.5,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num2-typ': {
            'default': default,
            'axtitle': False,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'xlabel': '$\ln\ln t$',
            'ylabel': '$\overline S_\mathrm{N,typical}$',
            'yformat': '%.3f',
            'ystat': 'typ',
            # 'yscale': 'log',
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 0.0,
            # 'xmax': 2.5,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num1num1': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': ['number_entropy'],
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'xlabel': '$t$',
            'ylabel': '$\overline S_\mathrm{N}',
            'plotprefix': 'SNSN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.008,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',

            'zoomloglogwindow': {
                'colnum': [0],  # Which columns (colname) to zoom in on
                'pos': [0.125, 0.10, 0.42, 0.42],
                # 'pos': [0.03, 0.6, 0.32, 0.32],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                # 'legendtitle': '$S_\mathrm{N}$'
            },
            'linestyle': ['solid', 'dashed'],
        },
        'numH1': {  # Hartley number entropy
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'hartley_number_entropy',
            'normpage': False,
            'titlename': ' Hartley Number Entropy',
            'ylabel': '$\overline S_H$',
            'yformat': '%.2f',
            # 'ymin': 1.26,
            'ymin': 0,
            'ymax': 1.5,
            'plotprefix': 'SH',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendcols': ['f', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            
            
            'legendlocation': 'lower right',
        },
        'numH2': {  # Hartley number entropy
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x1,
            'subplots': subplots2x1,
            'groupname': 'measurements',
            'colname': 'hartley_number_entropy',
            'normpage': False,
            'titlename': ' HartleyNumber Entropy',
            'ylabel': '$\overline S_H$',
            'yformat': '%.2f',
            # 'ymin': 1.27,
            'ymin': 0,
            'ymax': 1.5,
            'plotprefix': 'SH',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            'legendcols': ['f', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
        },
        'numa': {
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'filter': {
                'L': [16,20,24,28],
            },
            # 'titlename': 'Number Entropy Approach to saturation',
            'ylabel': '$|\overline S_\mathrm{N}^\infty - \overline S_\mathrm{N}|$',
            'xlabel': '$t$',
            # 'yformat': '%.2f',
            'yscale': 'log',
            'xticks': [1e0,1e2,1e4],
            'xmaloc': LogLocator(base=10, numticks=5, numdecs=7),
            'xmafmt': LogFormatterMathtext(labelOnlyBase=True),
            'ymin' : 2e-4,
            'ymax' : 5e-2,
            'xmin':5e-1,
            'xmax': 3e5,
            'plotprefix': 'SNA',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': False,
            'plotsatapproach': True,
            'usescatterplot' : False,
            'fillerror': False,
            'marksatapproach': True,
            'timeselection': 'lnt',
            'timenormalization':'',
            'mplstyle': mplstyle,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
            # 'legendlocation': (0.55, 0.44),
            'legendlocation': 'upper right',
            'bbox_to_anchor': (1.05,1.05),
        },
        'numa-lnlnt': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'filter': {
                'L': [12, 16, 20, 24, 28, 32],
            },
            # 'titlename': 'Number Entropy Approach to saturation',
            'ylabel': '$|\overline S_\mathrm{N}^\infty - \overline S_\mathrm{N}|$',
            'xlabel': '$\ln \ln t$',
            # 'yformat': '%.2f',
            # 'yscale': 'linear',
            'xticks': [0,1,2],
            # 'xmaloc': LogLocator(base=10, numticks=5, numdecs=7),
            # 'xmafmt': LogFormatterMathtext(labelOnlyBase=True),
            'ymin': -0.004,
            'ymax': 0.023,
            'xmin':-0.2,
            'xmax': 2.5,
            'plotprefix': 'SNA-lnlnt',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': False,
            'plotsatapproach': True,
            'fitsatapproachpower': False,
            'fitsatapproachlnlnt': True,
            'usescatterplot': False,
            'fillerror': False,
            'marksatapproach': True,
            'timeselection': 'lnlnt',
            'timenormalization': '',
            'mplstyle': mplstyle,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'

            # 'legendlocation': (0.55, 0.44),
            'legendlocation': 'upper right',
            'bbox_to_anchor': (1.08, 1.06),
        },

        'numHa': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'hartley_number_entropy',
            'normpage': False,
            'titlename': 'Hartley Number Entropy Approach to saturation',
            'ylabel': '$|S_\mathrm{H}(L/2, t) - \\tilde{S}_\mathrm{H}(L/2)|$',
            # 'yformat': '%.2f',
            'yscale': 'log',
            'plotprefix': 'SHA',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': False,
            'plotsatapproach': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendcols': ['f', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            
            
            'legendlocation': 'lower left',
        },
        'nument1': {
            'default' : default,
            'groupname': 'measurements',
            'colname': ['number_entropy', 'entanglement_entropy'],
            'normpage': False,
            'titlename': 'Entanglement and Number Entropies',
            'ylabel': '$\langle S(L/2)\\rangle$',
            'plotprefix': 'SESN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'zoomloglogwindow': {
                'colnum': [0],  # Which columns (colname) to zoom in on
                # 'pos': [0.03, 0.6, 0.40, 0.40], # Positon of the inset, x0 y0 width height
                'pos': [0.5, 0.35, 0.35, 0.35],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                'legendtitle': '$S_\mathrm{N}$'
            },
            'timeselection': 'lnt',
            'linestyle': ['solid', 'dashed'],
            'mplstyle': mplstyle,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'upper left',
        },
        'nument2': {
            'default' : default,
            'groupname': 'measurements',
            'colname': ['number_entropy', 'entanglement_entropy'],
            'normpage': False,
            'titlename': 'Entanglement and Number Entropies',
            'ylabel': '$\langle S(L/2)\\rangle$',
            'plotprefix': 'SESN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'zoomloglogwindow': {
                'colnum': [0],  # Which columns (colname) to zoom in on
                'pos': [0.03, 0.6, 0.32, 0.32],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                'legendtitle': '$S_\mathrm{N}$'
            },
            'timeselection': 'lnt',
            'linestyle': ['solid', 'dashed'],
            'mplstyle': mplstyle,
            'legendoutside': False,
            'legendcollect': False,
            'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
        },
        'num1-ren2': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N}^{(2)}$',
            'xlabel': '$t$',
            'yformat': '%.2f',
            # 'yscale': 'log',
            'plotprefix': 'SN-renyi2',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'plotrenyi2': True,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num2-ren2': {
            'default' : default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter':{
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'ylabel': '$\overline S_\mathrm{N}^{(2)}$',
            'xlabel': '$\ln\ln t$',
            'yformat': '%.2f',
            # 'yscale': 'log',
            'plotprefix': 'SN-renyi2',
            'plotrenyi2': True,
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            'xticks': [-1,0,1,2,3],
            'ytickparams': {
                'axis' : 'y',
                'direction': 'in',
                'pad' : -22,
            },

            'ylabel_inner_visible': False,
            # 'ymin': 0.31,
            # 'ymax': 0.36,
            'xmin': -1.5,
            'xmax': 3.6,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marklogwindow': True,
            'marksaturation': True,
            'findloglogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.008,
            'fitloglogwindow': False,
            'fillerror': False,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': ['upper left','center right','upper left','center right'],
            'bbox_to_anchor': [(-0.05, 1.05),(1.05, 0.55),(-0.05, 1.05),(1.05, 0.55)],  # Use with loc 'upper right'
        },
        'num1-hartley': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'ylabel': '$\overline S_\mathrm{N}^{H}$',
            'xlabel': '$t$',
            'yformat': '%.2f',
            # 'yscale': 'log',
            'plotprefix': 'SN-hartley',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.120,
            # 'ymax': 0.325,
            # 'xmin': 5e-1,
            # 'xmax': 5e+3,
            'plothartley': True,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marksaturation': True,
            'findloglogwindow': True,
            'marklogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.005,
            'fitloglogwindow': True,
            'fillerror': True,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'lower right',
            # 'legendlocation': (0.01, 0.65),
        },
        'num2-hartley': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'ylabel': '$\overline S_\mathrm{N}^{H}$',
            'xlabel': '$\ln\ln t$',
            'yformat': '%.3f',
            # 'yscale': 'log',
            'plotprefix': 'SN-hartley',
            'plothartley': True,
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            'xticks': [-1, 0, 1, 2, 3],
            'ytickparams': {
                'axis': 'y',
                'direction': 'in',
                'pad': -28,
            },

            'ylabel_inner_visible': False,
            # 'ymin': 0.31,
            # 'ymax': 0.36,
            'xmin': -0.5,
            # 'xmax': 2.5,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'marklogwindow': True,
            'marksaturation': True,
            'findloglogwindow': True,
            'markloglogwindow': True,
            'markloglogoffset': 0.008,
            'fitloglogwindow': False,
            'fillerror': False,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            'legendshow': True,
            'legendoutside': False,
            'legendcollect': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': ['upper left', 'center right', 'upper left', 'center right'],
            'bbox_to_anchor': [(-0.05, 1.05), (1.05, 0.55), (-0.05, 1.05), (1.05, 0.55)],  # Use with loc 'upper right'
        },
        'numa-hartley': {
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'f': [0.3,0.5],
                # 'u': [16],
            },
            'ylabel': '$|\overline (S_\mathrm{N}^\mathrm{H})^\infty - \overline S_\mathrm{N}^\mathrm{H}|$',
            'xlabel': '$\ln\ln t$',
            'yformat': '%.3f',
            # 'yscale': 'log',
            'plotprefix': 'SN-hartley',
            'plothartley': True,
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            'xticks': [-1, 0, 1, 2, 3],
            'ytickparams': {
                'axis': 'y',
                'direction': 'in',
                'pad': -28,
            },

            'ylabel_inner_visible': False,
            'ymin': -0.003,
            'ymax': 0.010,
            'xmin': -0.5,
            'xmax': 2.5,
            'marklogwindow': True,
            'marksaturation': True,
            'markloglogoffset': 0.008,
            'legendshow': True,
            'legendoutside': False,
            'legendcollect': False,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': False,
            'fitloglogwindow': False,
            'plotsatapproach': True,
            'fitsatapproachpower': False,
            'fitsatapproachlnlnt': True,
            'usescatterplot': False,
            'fillerror': False,
            'marksatapproach': True,
            'timeselection': 'lnlnt',
            'timenormalization': '',
            'mplstyle': mplstyle,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
            # 'legendlocation': (0.55, 0.44),
            'legendlocation': 'upper right',
            'bbox_to_anchor': (1.08, 1.06),
        },
        'chi': {
            'default' : default,
            'groupname': 'measurements',
            'colname': ['bond_mid'],
            'titlename': 'Midchain Bond Dimension',
            'ylabel': '$\langle\chi\\rangle$',
            'plotprefix': 'chi',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendoutside': False,
            'legendcollect': False,
            'legendcols': ['bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'best',
        },
        'tsim': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'algorithm_time',
            'titlename': 'Simulation Time',
            'ylabel': 'Avg. Simulation Time [min]',
            'yscale': 'log',
            'plotprefix': 'tsim',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'normalize': 60,
            'realizations': 600,
            'findsaturation': False,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendoutside': False,
            'legendcollect': False,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
            
            
        },
        'titr': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'algorithm_time',
            'titlename': 'Iteration Time',
            'ylabel': 'Avg Iteration Time [min]',
            'ydiff': True,  # Plot the difference in y instead.
            'yscale': 'log',
            'plotprefix': 'titr',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'normalize': 60,
            'realizations': 600,
            'findsaturation': False,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
        },
        'trn': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'truncation_error',
            'normpage': False,
            'titlename': 'Truncation Error',
            'ylabel': '$\epsilon$',
            'yscale': 'log',
            'sharex': 'all',
            'sharey': 'all',
            # MultipleLocator(tick_spacing)
            # 'xmaloc': LogLocator(base=10, numticks=99, numdecs=16),
            # 'xmiloc': LogLocator(base=10, numticks=99, subs=(.1, .2, .3, .4, .5, .6, .7, .8, .9)),
            # 'xmafmt': LogFormatter(base=10.0, labelOnlyBase=True, minor_thresholds=(1.0, 0.4), linthresh=None),
            # 'xmaloc': LogLocator(numticks=9, numdecs=32),
            # 'xmiloc': LogLocator(subs=(.1, .2, .3, .4, .5, .6, .7, .8, .9)),
            'xmafmt': LogFormatterMathtext(labelOnlyBase=True),

            'plotprefix': 'eps',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'findsaturation': False,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'markloglogwindow': False,
            'timeselection': 'lnt',
            'mplstyle': mplstyle,
            'legendoutside': False,
            'legendcollect': False,
            'legendcols': ['w', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendlocation': 'best',
        },
        'lbit-avg': {
                        'default' : default,
            # 'figsize': (1.702, 1.702),
            'figsize': figsize1x1_fullcol,
            'subplots': subplots1x1,
            'frameon': True,
            'groupname': 'lbits',
            'dsetname': 'corrmat',
            #'titlename': 'l-bit decay fit $C e^{-(|i-j|/\\xi)^\\beta}$',
            # 'filter': {
                # 'L': [24],
                # 'f': [0.2,0.4],
                # 'u': [16],
            # },
            # 'titlename': 'l-bit decay fit $C e^{-|i-j|/\\xi}$',
            # 'ylabel': '$\log_{10} \langle \langle O(|i-j|) \\rangle\\rangle$ ',
            'ylabel': '$\\bar O(|i-j|)$',
            # 'ylabel': '$\log_{10} \\bar O(|i-j|)$ ',
            'xlabel': "$j$",
            # 'xticks': [0, 0.25, 0.5, 0.75, 1.0] if prb else None,
            'xticks': [0, 5, 10, 15, 20] if prb else None,
            'yticks': None, #[1, 1e-3, 1e-6, 1e-9, 1e-12, 1e-15],
            # 'yticks': [0, -3, -6, -9, -12, -15],
            'yscale': 'log',
            'ynopos': 'mask',
            'plotprefix': 'lbit-arithmetic',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            # 'ymin': -16,
            'ymin': 1e-16,
            # 'xmax': 20,
            # 'xmin': -1,
            'xnormalize': True,
            # 'xmax': 32 if prb else None,
            # 'ymin': 1e-14,
            # 'legendcols': ['f', 'tstd', 'tgw8', 'cstd', 'cgw8', 'ubond'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'] if prb else [],  # Choose 'num', 'bmax','tsim'
            'legendfits': ['xi', 'beta'] if prb else ['C', 'xi', 'beta', 'pos'],
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': (0.14, 1.025) if prb else 'center left',
            'legendtitle': 'Arithmetic average',
            # 'legendtitle': '$y = C e^{-|i-j|/\\xi_\\tau}$',
            # 'legendtitle': '$\log \\bar O(x) = a - x \\xi_\\tau^{-1}$',
            'lbit-site': [0, 'mid', 'last'],
            'lbit-mean': 'arithmetic',
            'lbit-axis': '',
            'fit-beta': True,
            'fit-ymin': None,
            'fit-skip': 0 if prb else 0,
            'fit-mark': False,
            'fit-plot': True,
            'inset-cls': {
                # 'pos': [0.03, 0.6, 0.40, 0.40], # Positon of the inset, x0 y0 width height
                'pos': [0.17, 0.15, 0.25, 0.25],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                'legendtitle': '$\\xi_\\tau$',
            },
        },
        'lbit-typ': {
            'default': default,
            # 'figsize': (1.702, 1.702),
            'figsize': figsize1x1_fullcol,
            'subplots': subplots1x1,
            'frameon': True,
            'groupname': 'lbits',
            'dsetname': 'corrmat',
            # 'titlename': 'l-bit decay fit $C e^{-(|i-j|/\\xi)^\\beta}$',
            # 'filter': {
            # 'L': [24],
            # 'f': [0.2,0.4],
            # 'u': [16],
            # },
            # 'titlename': 'l-bit decay fit $C e^{-|i-j|/\\xi}$',
            # 'ylabel': '$\log_{10} \langle \langle O(|i-j|) \\rangle\\rangle_\mathrm{geom.}$',
            # 'ylabel': '$\langle \langle O(|i-j|) \\rangle\\rangle$',
            # 'ylabel': '$\log_{10} \\bar O(|i-j|)$ ',
            'xlabel': "$j$",
            # 'xticks': [0, 0.25, 0.5, 0.75, 1.0] if prb else None,
            'xticks': [0, 5, 10, 15, 20] if prb else None,
            # 'yticks': [1e0, 1e-4, 1e-9],
            'yticks': None,  # [0, -3, -6, -9, -12, -15],
            'yticklabels': [],
            'yscale': 'log',
            'ynopos': 'mask',
            'plotprefix': 'lbit-geometric',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            # 'ymin': -16,
            'ymin': 1e-16,
            # 'xmax': 20,
            # 'xmin': -1,
            'xnormalize': True,
            # 'xmax': 32 if prb else None,
            # 'ymin': 1e-14,
            # 'legendcols': ['f', 'tstd', 'tgw8', 'cstd', 'cgw8', 'ubond'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'] if prb else [],  # Choose 'num', 'bmax','tsim'
            'legendfits': ['xi', 'beta'] if prb else ['C', 'xi', 'beta', 'pos'],
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': (0.14, 1.025) if prb else 'center left',
            'legendtitle': 'Geometric average',
            # 'legendtitle': '$y = C e^{-|i-j|/\\xi_\\tau}$',
            # 'legendtitle': '$\log \\bar O(x) = a - x \\xi_\\tau^{-1}$',
            'lbit-site': [0, 'mid', 'last'],
            'lbit-mean': 'geometric',
            'lbit-axis': '',
            'fit-beta': True,
            'fit-ymin': None,
            'fit-skip': 0 if prb else 0,
            'fit-mark': False,
            'fit-plot': True,
            'inset-cls': {
                # 'pos': [0.03, 0.6, 0.40, 0.40], # Positon of the inset, x0 y0 width height
                'pos': [0.17, 0.15, 0.25, 0.25],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                'legendtitle': '$\\xi_\\tau$',
            },
        },

        'cls-avg': {
            'default' : default,
            'groupname': 'lbits',
            'dsetname': 'corrmat',
            'titlename': '$\ell$-bit localization length (arithmetic avg.)',
            'filter': {
                # 'L': [8,12,16,20],
                # 'f': [0.2, 0.3, 0.4, 0.6, 0.8, 1.0],
                # 'u': [4, 8, 12, 16],
            },
            'ylabel': '$\langle\langle \\xi_\\tau \\rangle\\rangle$',
            # 'yticks': [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4] if prb else None,
            # 'xticks': [16,32,48,64,80],
            'plotprefix': 'cls-avg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            'legendcols': [] if prb else ['f', 'x'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': True,
            'legendcollect': True,
            'legendfits': ['xi', 'beta'] if prb else ['C', 'xi', 'beta', 'pos'],
            'lbit-site': ['mid'],
            'lbit-mean': 'arithmetic',
            'fit-beta': True,
            'fit-ymin': None,
            'fit-skip': 0 if prb else 0,
            # 'legendlocation': 'best',
            'legendlocation': 'best',  # "(0.52, 0.05),
        },
        'cls-typ': {
            'default' : default,
            'groupname': 'lbits',
            'dsetname': 'corrmat',
            'titlename': '$\ell$-bit localization length (geometric avg.)',
            'filter': {
                # 'L': [8,12,16,20],
                # 'f': [0.2, 0.3, 0.4, 0.6, 0.8, 1.0],
                #'u': [4, 8, 12, 16],
            },
            'ylabel': '$\langle\langle \\xi_\\tau \\rangle\\rangle$',
            # 'yticks': [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4] if prb else None,
            # 'xticks': [16,32,48,64,80],
            'plotprefix': 'cls-typ',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            'legendcols': [] if prb else ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': True,
            'legendcollect': True,
            'legendfits': ['xi', 'beta'] if prb else ['C', 'xi', 'beta', 'pos'],
            'lbit-site': ['mid'],
            'lbit-mean': 'geometric',
            'fit-beta': True,
            'fit-ymin': None,
            'fit-skip': 0 if prb else 0,
            # 'legendlocation': 'best',
            'legendlocation': 'best',  # "(0.52, 0.05),
        },
        'dist-num': {
            'default' : default,
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            'titlename': 'Number Entropy',
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p(S_\mathrm{N})$',
            'yscale': 'log',
            # 'yformat': '%.2f',
            'sharex': 'all',
            'sharey': 'all',
            'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'xlabel': '$S_\mathrm{N}$',
            'density': True,
            'plotprefix': 'SN',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'f', 'w', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'w', 'num', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'lower left',
        },
        'divg-ent': {  # Distribution of infinite time averaged entropy
            'default' : default,
            'axtitle' : True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'dsetname': 'entanglement_entropy',
            'normpage': False,
            # 'titlename': 'Entanglement Entropy',
            # 'figsize': (3.375, 3.00),
            'xticks': [0,1,2,3,4,5],
            'ylabel': '$p(S_\mathrm{E}^\infty)$',
            'yscale': 'log',
            # 'yformat': '%.2f',
            'ymaloc': LogLocator(numticks=9),  # FixedLocator([1e-3,1e-2,1e-1,1e0,1e1]),
            'sharex': 'all',
            'sharey': 'all',
            'xmin': 0.0,
            'xmax': 5.5,
            'ymax': 3.0,#4.75,
            'ymin': 5e-4,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'range': (0, 5.0),
            'xlabel': '$S_\mathrm{E}^\infty$',
            'density': True,
            'plotprefix': 'SE-divg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'w'],  # Choose 'num', 'bmax','tsim'
            'legendshow': True,
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            # 'legendlocation': 'upper right',
            'legendlocation': ['upper right', 'upper right', 'upper right', 'upper right', ],
            'bbox_to_anchor': (1.05, 1.05),  # Use with loc 'upper right'
            'legend2location': 'upper right',
            # 'bbox_to_anchor2': (1.05, 0.40),  # Use with loc 'upper right'
            'bbox_to_anchor2': (0.825, 0.95),  # Use with loc 'upper right'
        },
        'divg-num': {  # Distribution of infinite time averaged entropy
            'default' : default,
            'axtitle' : True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                #'L': [12, 16, 20],
                #'f': [0.2,0.3,0.4,0.5],
                #'u': [16],
            },
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p(S_\mathrm{N}^\infty)$',
            'yscale': 'log',
            # 'yformat': '%.2f',
            'ymaloc': LogLocator(numticks=9), #FixedLocator([1e-3,1e-2,1e-1,1e0,1e1]),
            # 'ymafmt': LogFormatterMathtext(labelOnlyBase=True),
            'sharex': 'all',
            'sharey': 'all',
            'xmin': 0.0,
            'xmax': 1.2,
            'ymin': 1e-3,
            'ymax': 25,
            'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'range': (0, 1.2),
            'xlabel': '$S_\mathrm{N}^\infty$',
            'density': True,
            'marklog2':True,
            'marklog3':True,
            'plotprefix': 'SN-divg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'w'],  # Choose 'num', 'bmax','tsim'
            'legendshow' : True,
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            # 'legendlocation': 'lower left',
            'legendlocation': ['upper right', 'upper right', 'upper right', 'upper right', ],
            'bbox_to_anchor': (0.92, 1.05),  # Use with loc 'upper right'
            'legend2location': 'lower left',
            # 'bbox_to_anchor2': (1.05, 0.40),  # Use with loc 'upper right'
            # 'bbox_to_anchor2': (0.825, 0.95),  # Use with loc 'upper right'
        },
        'zivg-num': {  # Zoomed Distribution of infinite time averaged entropy
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'L': [12, 16, 20],
                # 'f': [0.2,0.3,0.4,0.5],
                # 'u': [16],
            },
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p(S_\mathrm{N}^\infty)$',
            'yscale': 'log',
            'xticks': [0.4, 0.5,0.6, 0.7],
            # 'yticks': [0.4, 1.0, 3.0],
            'ymaloc': FixedLocator([0.4, 1, 3]),
            'ymafmt': ScalarFormatter(),
            # 'yformat': '%.1f',
            'sharex': 'all',
            'sharey': 'all',
            'xmin': 0.35,
            'xmax': 0.79,
            'ymin': 0.29,
            'ymax': 5.10,
            'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'range': (0,1.2),
            'xlabel': '$S_\mathrm{N}^\infty$',
            'density': True,
            'marklog2': True,
            'plotprefix': 'SN-divg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'w'],  # Choose 'num', 'bmax','tsim'
            'legendshow': False,
            'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            # 'legendlocation': 'lower left',
            # 'legendlocation': 'lower left',
            'legendlocation': ['upper right', 'upper right', 'upper right', 'upper right', ],
            'bbox_to_anchor': (1.07, 1.05),  # Use with loc 'upper right'
            'legend2location': 'upper left',
            # 'bbox_to_anchor2': (1.05, 0.40),  # Use with loc 'upper right'
            # 'bbox_to_anchor2': (0.825, 0.95),  # Use with loc 'upper right'

        },
        'pivg-num': {  # Distribution of infinite time averaged entropy
            'default': default,
            'axtitle': True,
            'figsize': figsize2x2,
            'subplots': subplots2x2,
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Number Entropy',
            'filter': {
                # 'L': [12, 16, 20],
                # 'f': [0.2,0.3,0.4,0.5],
                # 'u': [16],
            },
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p\left[S(p_\mathrm{N}^\infty)\\right]$',
            'yscale': 'log',
            # 'yformat': '%.2f',
            'ymaloc': LogLocator(numticks=9),  # FixedLocator([1e-3,1e-2,1e-1,1e0,1e1]),
            # 'ymafmt': LogFormatterMathtext(labelOnlyBase=True),
            'sharex': 'all',
            'sharey': 'all',
            'xmin': 0.0,
            'xmax': 1.2,
            'ymin': 1e-3,
            'ymax': 25,
            'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'range': (0, 1.2),
            'xlabel': '$S(p_\mathrm{N}^\infty)$',
            'density': True,
            'marklog2': True,
            'marklog3': True,
            'plotpinfty':True,
            'plotprefix': 'SN-pivg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'w'],  # Choose 'num', 'bmax','tsim'
            'legendshow': True,
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'lower left',
        },
        'dist-mem': {  # Distribution of infinite time averaged entropy
            'default' : default,
            'groupname': 'mem_usage',
            'dsetname': 'data',
            'colname' : 'hwm',
            'titlename': 'Max Memory Usage',
            'filter': {
                # 'L': [12, 16, 20],
                # 'f': [0.2,0.3,0.4,0.5],
                # 'u': [16],
            },
            # 'figsize': (3.375, 3.00),
            'ylabel': 'Histogram',
            'yscale': 'log',
            # 'yformat': '%.2f',
            'sharex': 'all',
            'sharey': 'all',
            # 'xmin': 0.0,
            # 'xmax': 1.2,
            # 'ymin': 1e-5,
            # 'tidx': 'window',  # Time indices for which to plot the distribution
            'bins': 100,
            'xlabel': 'RAM [MB]',
            'density': False,
            'plotprefix': 'mem',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'w'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
        },
        'tavg-ent': {
            'default' : default,
            # 'figsize': figsize1x1_fullcol,
            'figsize': (3.404*0.80, 3.404*0.5),
            # 'subplots': subplots1x1,
            'subplots': {
                'top': 1.0,
                'bottom': 0.14,
                'left': 0.11,
                'right': 0.80,
            },
            'groupname': 'measurements',
            'dsetname': 'entanglement_entropy',
            'normpage': False,
            'normsize': False,
            # 'titlename': 'Average Entanglement entropy as $t\\rightarrow \infty$',
            'ylabel': '$\overline S_\mathrm{E}^\infty$',
            'yformat': '%.1f',
            'xticks': [12,16,20,24,28,32],
            # 'xmaloc': MaxNLocator(integer=True),
            'sharex': 'None',
            'sharey': 'None',
            'xlabel': '$L$',
            'density': True,
            'ystats' : ['mean'],
            'ytwinx' : False,
            'plotprefix': 'SE-tavg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper left',
            'bbox_to_anchor': (0.95, 1.05),  # Use with loc 'upper right'
        },
        'tavg-ent-page': {
            'default': default,
            'figsize': figsize1x1_fullcol,
            'subplots': subplots1x1,
            'groupname': 'measurements',
            'dsetname': 'entanglement_entropy',
            'normpage': True,
            # 'titlename': 'Average Entanglement entropy as $t\\rightarrow \infty$',
            'ylabel': '$\overline S_\mathrm{E}^\infty / S_\mathrm{Page}$',
            'yformat': '%.2f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True),
            'sharex': 'None',
            'sharey': 'None',
            'ytickparams': {
                'axis': 'y',
                'direction': 'in',
                'pad': -22,
            },
            'xlabel': '$L$',
            'density': True,
            'ystats': ['mean'],
            'plotprefix': 'SE-tavg-page',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': [],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'lower right',
        },
        'tgvg-ent': {
            'default': default,
            'groupname': 'measurements',
            'dsetname': 'entanglement_entropy',
            'normpage': False,
            # 'titlename': 'Average Entanglement entropy as $t\\rightarrow \infty$',
            'figsize': (1.702,1.702),
            'ylabel': '$\overline S_\mathrm{E}^\infty$',
            'yformat': '%.2f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True),
            'sharex': 'all',
            'sharey': 'all',
            'xlabel': '$L$',
            'density': True,
            'ystats': ['gmean'],
            'plotprefix': 'SE-tgvg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'lower right',
        },
        'tavg-num': {
            'default' : default,
            'axtitle': True,
            # 'figsize': figsize1x1_fullcol,
            # 'subplots': subplots1x1,
            'figsize': (3.404, 0.88*3.404),
            'subplots': {
                'top': 0.96,
                'bottom': 0.09,
                'left': 0.14,
                'right': 0.90,
                'wspace': 0.00,
                'hspace': 0.00,
            },
            # 'figsize' : (3.404*0.68, 3.404),
            # 'subplots': {
            #     'top': 1.0,
            #     'bottom': 0,
            #     'left': 0.22,
            #     'right': 0.85,
            # },
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Average Number Entropy as $t\\rightarrow \infty$',
            # 'ylabel': '$\overline S_\mathrm{N}^\infty$',
            'ylabel': '$\overline S_\mathrm{N}^\infty, \overline S(p_\mathrm{N}^\infty)$',
            # 'ylabel': '$lower S_\mathrm{N}$',
            'yformat': '%.3f',
            'xticks': [12, 16, 20,24,28, 32],
            # 'xmaloc': MaxNLocator(integer=True, nbins=4),
            'sharex': 'all',
            'sharey': 'none',
            'xlabel': '$L$',
            'ystats': ['mean'],
            'ytwinx': False,
            'ytickparams': {
                'direction': 'in',
                'pad': 4,
                'tick_right': True
            },
            # 'Wselection':{
            #     'W8.0': ('f0.2', 'RPS'),
            #
            # }
            'density': True,
            'plotprefix': 'SN-tavg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'plotluitz': False,
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            'xmin': 10,
            'xmax': 34,
            'mplstyle': mplstyle,
            'plotpinfty': True,
            'legendshow': False,
            'legendshow2': False,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'u', 'f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': ['upper right', 'upper right','lower right','lower right'],
            # 'bbox_to_anchor': [(1.05, 1.05)],  # Use with loc 'upper right'
        },
        'tavg-num-aio': {
            'default': default,
            # 'figsize': figsize1x1_fullcol,
            # 'subplots': subplots1x1,
            'figsize': figsize1x1_fullcol,
            'subplots': subplots1x1,
            # 'figsize' : (3.404*0.68, 3.404),
            # 'subplots': {
            #     'top': 1.0,
            #     'bottom': 0,
            #     'left': 0.22,
            #     'right': 0.85,
            # },
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Average Number Entropy as $t\\rightarrow \infty$',
            # 'ylabel': '$\overline S_\mathrm{N}^\infty$',
            'ylabel': '$\overline S_\mathrm{N}^\infty, \overline S(p_\mathrm{N}^\infty)$',
            'yformat': '%.2f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True, nbins=4),
            'sharex': 'none',
            'sharey': 'none',
            'xlabel': '$L$',
            'ystats': ['mean'],
            'ytwinx': False,
            # 'ytickparams': {
            #     'axis': 'y',
            #     'direction': 'in',
            #     'pad': -22,
            # },
            'density': True,
            'plotprefix': 'SN-tavg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'mplstyle': mplstyle,
            'plotpinfty': True,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'u', 'f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
            'bbox_to_anchor': (1.05, 1.05),  # Use with loc 'upper right'
        },
        'tgvg-num': {
            'default': default,
            'figsize': figsize1x1_fullcol,
            'subplots': subplots1x1,
            # 'figsize': (3.404 * 0.68, 3.404),
            # 'subplots': {
            #     'top': 1.0,
            #     'bottom': 0,
            #     'left': 0.22,
            #     'right': 0.85,
            # },
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Average Number Entropy as $t\\rightarrow \infty$',
            'ylabel': '$\overline S_\mathrm{N}^\infty$',
            'yformat': '%.3f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True, nbins=4),
            'sharex': 'none',
            'sharey': 'none',
            'xlabel': '$L$',
            'ystats': ['gmean'],
            'ytwinx': False,
            # 'ytickparams': {
            #     'axis': 'y',
            #     'direction': 'in',
            #     'pad': -22,
            # },
            'density': True,
            'plotprefix': 'SN-tgvg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'plotpinfty': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'u', 'f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
        },
        'tgvg-num-old': {
            'default': default,
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Average Number Entropy as $t\\rightarrow \infty$',
            'figsize': (1.702,1.702),
            'ylabel': '$\overline S_\mathrm{N}^\infty$',
            'yformat': '%.2f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True, nbins=4),
            'sharex': 'all',
            'sharey': 'all',
            'xlabel': '$L$',
            'ystats': ['gmean'],
            'density': True,
            'plotprefix': 'SN-tgvg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'u', 'f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'lower right',
        },
        'pavg-num': {
            'default': default,
            'figsize' :  (3.404, 3.404),
            'subplots' : {
                'top': 0.96,
                'bottom': 0.09,
                'left': 0.14,
                'right': 0.90,
                'wspace':0.00,
                'hspace':0.00,
            },
            # 'figsize': (3.404 * 0.68, 3.404),
            # 'subplots': {
            #     'top': 1.0,
            #     'bottom': 0,
            #     'left': 0.22,
            #     'right': 0.85,
            # },
            'groupname': 'measurements',
            'dsetname': 'number_entropy',
            'normpage': False,
            # 'titlename': 'Average Number Entropy as $t\\rightarrow \infty$',
            'ylabel': '$\overline S(p_\mathrm{N}^\infty)$',
            'yformat': '%.3f',
            'xticks': [12, 16, 20, 24, 28, 32],
            # 'xmaloc': MaxNLocator(integer=True, nbins=4),
            'sharex': 'none',
            'sharey': 'none',
            'xlabel': '$L$',
            'ystats': ['mean'],
            'ytwinx': False,
            # 'ytickparams': {
            #     'axis': 'y',
            #     'direction': 'in',
            #     'pad': -22,
            # },
            'density': True,
            'plotprefix': 'SN-pavg',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'plotpinfty': True,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'u', 'f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'num'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['f'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
        },
        'dist-tsim': {
            'default' : default,
            'groupname': 'measurements',
            'dsetname': 'algorithm_time',
            'normpage': False,
            'titlename': 'Simulation time',
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p(t_\mathrm{sim})$',
            'yscale': 'log',
            'xscale': 'log',
            # 'yformat': '%.2f',
            'sharex': 'all',
            'sharey': 'all',
            'tidx': [-1],  # Time indices for which to plot the distribution
            'bins': 100,
            'normalize': 60,
            'xlabel': '$t_\mathrm{sim}$',
            'density': True,
            'plotprefix': 'tsim',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'ymin': 1e-4,
            'xmin': 5e-2,
            'xmax': 1e+3,
            'findsaturation': False,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'markloglogwindow': False,
            'fitloglogwindow': False,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'f', 'w', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'tsim'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'w', 'num', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
        },
        'dist-chi': {
            'default' : default,
            'groupname': 'measurements',
            'dsetname': 'bond_mid',
            'normpage': False,
            'titlename': 'Midchain Bond dimension ($t\\rightarrow\infty)$',
            # 'figsize': (3.375, 3.00),
            'ylabel': '$p(\chi)$',
            # 'yscale': 'log',
            'xscale': 'log',
            # 'yformat': '%.2f',
            'sharex': 'all',
            'sharey': 'all',
            'tidx': [-1],  # Time indices for which to plot the distribution
            'bins': 100,
            'xlabel': '$\chi$',
            'density': True,
            'plotprefix': 'bond',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            # 'ymin': 0.41,
            # 'ymax': 0.45,
            # 'xmin': 1,
            'findsaturation': False,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': False,
            'markloglogwindow': False,
            'fitloglogwindow': False,
            # 'timeselection': 'lnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim', 't:.1e'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['L', 'f', 'w', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'tsim'],  # Choose 'num', 'bmax','tsim'
            # 'legendcols': ['f', 'x', 'w', 'num', 't:<8.1e'],  # Choose 'num', 'bmax','tsim'
            'legendoutside': False,
            'legendcollect': False,
            'legendlocation': 'upper right',
        },
        'linearFit-num2': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'titlename': 'Number Entropy fit to $\\alpha + \\beta \log \log t$',
            'ylabel': '$\\beta$',
            'yformat': '%.3f',
            'plotprefix': 'SN-linearFit',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            # 'xmin': 0.0,
            # 'xmax': 2.1,
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': False,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f', 'tstd', 'tgw8', 'cstd', 'cgw8'],  # Choose 'num', 'bmax','tsim'
            
            
            'legendlocation': 'center left',
            # 'legendlocation': (0.01, 0.65),
        },
        'rise-num2': {
            'default' : default,
            'groupname': 'measurements',
            'colname': 'number_entropy',
            'normpage': False,
            'titlename': 'Number Entropy rise',
            'ylabel': '$S_\mathrm{N}(t_2) - S_\mathrm{N}(t_1)$',
            'yformat': '%.3f',
            'plotprefix': 'SN-rise',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'sharex': 'all',
            'sharey': 'none',
            # 'xmin': 0.0,
            # 'xmax': 2.75,
            'relative': False,
            'ylabel_relative': '$\\frac{S_\mathrm{N}(t_2) - S_\mathrm{N}(t_1)}{S_\mathrm{N}(t_2)}$',
            'findsaturation': True,  # Instead of taking the last value, take the average of the plateau
            'findloglogwindow': True,
            'markloglogwindow': True,
            'fitloglogwindow': True,
            'fillerror': False,
            'timeselection': 'lnlnt',
            'mplstyle': mplstyle,
            # 'legendcols': ['f', 'x', 'num', 'bmax:.0f', 'bavg:.0f', 'tsim'],  # Choose 'num', 'bmax','tsim'
            'legendcols': ['L', 'f'],  # Choose 'num', 'bmax','tsim'
            
            
            'legendlocation': 'center right',
            # 'legendlocation': (0.01, 0.65),
        },

        'crossup': {
            'default' : default,
            'groupname': 'lbits',
            'dsetname': 'corrmat',
            'titlename': '$\ell$-bit half-chain crossover',
            'filter': {
                # 'L': [8,12,16,20],
                # 'f': [0.2,0.3,0.4,0.5,1.0],
                # 'u': [16],
            },
            # 'titlename': 'l-bit decay fit $C e^{-|i-j|/\\xi}$',
            'ylabel': '$X_\ell$',
            # 'ylabel': '$\log_{10} \overline O(|i-j|)$ ',
            # 'xlabel': "$j$",
            # 'xticks': [0, 6, 12, 18] if prb else None,
            # 'yticks': [1e0, 1e-4, 1e-9],
            # 'yticks': [0, -3, -6, -9, -12, -15],
            # 'yscale': 'log',
            # 'ynopos': 'mask',
            'plotprefix': 'lbit',
            'plotdir': Path(plotdir, Path(mplstyle).stem),
            'mplstyle': mplstyle,
            # 'ymin': -16,
            # 'xmax': 32 if prb else None,
            # 'ymin': 1e-14,
            # 'legendcols': ['f', 'tstd', 'tgw8', 'cstd', 'cgw8', 'ubond'],  # Choose 'num', 'bmax','tsim'
            'legendcols': [] if prb else [],  # Choose 'num', 'bmax','tsim'
            'legendfits': ['xi', 'beta'] if prb else ['C', 'xi', 'beta', 'pos'],
            
            
            'legendlocation': 'lower right',
            # 'legendtitle': '$y = C e^{-|i-j|/\\xi_\\tau}$',
            # 'legendtitle': '$\log \overline O(x) = a - x \\xi_\\tau^{-1}$',
            'lbit-mean': 'arithmetic',
            'lbit-site': [0, 'mid', 'last'],

            'fit-beta': True,
            'fit-ymin': None,
            'fit-skip': 0 if prb else 0,
            'inset-cls': {
                # 'pos': [0.03, 0.6, 0.40, 0.40], # Positon of the inset, x0 y0 width height
                'pos': [0.17, 0.15, 0.25, 0.25],  # Positon of the inset, x0 y0 width height
                'coords': [None, None, None, None],
                # These zoom limits x1,x2,y1,y2, must be set by finding the maximum log log window
                'legendtitle': '$\\xi_\\tau$',
            },
        }

    }



    return meta
