
#find_package(Ceres PATHS ${EXTERNAL_INSTALL_DIR}/ceres/lib/cmake/Ceres ${ceres_DIR})

#if(Ceres_FOUND)
#    message(STATUS "ceres FOUND IN SYSTEM: ${CERES_ROOT}")
#    #    get_target_property(CERES_LIBRARY ceres  INTERFACE_LINK_LIBRARIES)
#    #    set_target_properties(ceres PROPERTIES INTERFACE_LINK_LIBRARIES "")
#    #    set_target_properties(ceres PROPERTIES INTERFACE_COMPILE_FEATURES "")
#    #    target_link_libraries(ceres INTERFACE  blas lapack lapacke ${CERES_LIBRARY} Threads::Threads )
#else()


    message(STATUS "Ceres will be installed into ${EXTERNAL_INSTALL_DIR}/ceres on first build.")
    get_target_property(EIGEN3_INCLUDE_DIR Eigen3::Eigen INTERFACE_INCLUDE_DIRECTORIES)
    list (GET EIGEN3_INCLUDE_DIR 0 EIGEN3_INCLUDE_DIR)
    if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
        set(CERES_LIBSUFFIX -debug)
    endif()

    get_target_property(GFLAGS_LIBRARIES    gflags      INTERFACE_LINK_LIBRARIES)
    get_target_property(GFLAGS_INCLUDE_DIR  gflags      INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(GLOG_LIBRARIES      glog::glog  INTERFACE_LINK_LIBRARIES)
    get_target_property(GLOG_INCLUDE_DIR    glog::glog  INTERFACE_INCLUDE_DIRECTORIES)
    unset(CERES_FLAGS CACHE)
    unset(CERES_FLAGS)
    if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
        set(CERES_FLAGS "${CERES_FLAGS} -O0 -g3 -fstack-protector -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2")
    elseif("${CMAKE_BUILD_TYPE}" MATCHES "RelWithDebInfo")
        set(CERES_FLAGS "${CERES_FLAGS} -O1 -g -fstack-protector -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2")
    else()
        set(CERES_FLAGS "${CERES_FLAGS} -O3 -DNDEBUG")
    endif()

    set(CERES_FLAGS "${CERES_FLAGS} -I${GLOG_INCLUDE_DIR} -I${GFLAGS_INCLUDE_DIR} ")
    string (REPLACE ";" " " CERES_FLAGS "${CERES_FLAGS}")
    list(APPEND CERES_CMAKE_OPTIONS  -DCERES_FLAGS:STRING=${CERES_FLAGS})
    list(APPEND CERES_CMAKE_OPTIONS  -DCUSTOM_SUFFIX:STRING=${CUSTOM_SUFFIX})
    list(APPEND CERES_CMAKE_OPTIONS  -DEIGEN3_INCLUDE_DIR:PATH=${EIGEN3_INCLUDE_DIR})
    list(APPEND CERES_CMAKE_OPTIONS  -DGFLAGS_INCLUDE_DIR:PATH=${GFLAGS_INCLUDE_DIR})
    list(APPEND CERES_CMAKE_OPTIONS  -DGFLAGS_LIBRARIES:PATH=${GFLAGS_LIBRARIES})
    list(APPEND CERES_CMAKE_OPTIONS  -DGLOG_INCLUDE_DIR:PATH=${GLOG_INCLUDE_DIR})
    list(APPEND CERES_CMAKE_OPTIONS  -DGLOG_LIBRARIES:PATH=${GLOG_LIBRARIES})

    message(STATUS "ceres flags: ${CERES_FLAGS}")
    include(${PROJECT_SOURCE_DIR}/cmake-modules/BuildDependency.cmake)
    build_dependency(ceres "${CERES_CMAKE_OPTIONS}")
    find_package(Ceres PATHS ${CMAKE_INSTALL_PREFIX}/ceres PATH_SUFFIXES REQUIRED)
    if(TARGET ceres)
        message(STATUS "ceres installed successfully")
        string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
        get_target_property(cereslib  ceres IMPORTED_LOCATION_${BUILD_TYPE})
        target_link_libraries(ceres INTERFACE ${cereslib})
    else()
        message(STATUS "config_result: ${config_result}")
        message(STATUS "build_result: ${build_result}")
        message(FATAL_ERROR "ceres could not be downloaded.")
    endif()

#endif()
