
function(remove_shared target_name)
    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    foreach(lib ${target_libs})
        if(NOT ${lib} MATCHES ".so")
            list(APPEND static_libs ${lib})
        endif()
    endforeach()
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${static_libs}")
endfunction()

find_package(glog 0.4 PATHS ${CMAKE_INSTALL_PREFIX}/glog $ENV{EBROOTGLOG} $ENV{GLOG_DIR} $ENV{glog_DIR} NO_DEFAULT_PATH)


if(TARGET glog::glog)
    message(STATUS "glog found")
    remove_shared(glog::glog)
    string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
    get_target_property(gloglib  glog::glog IMPORTED_LOCATION_${BUILD_TYPE})
    target_link_libraries(glog::glog INTERFACE ${gloglib})

elseif(DOWNLOAD_MISSING)
    message(STATUS "glog will be installed into ${CMAKE_INSTALL_PREFIX}")
    include(${PROJECT_SOURCE_DIR}/cmake-modules/BuildDependency.cmake)
    build_dependency(glog "")
    find_package(glog 0.4 PATHS ${CMAKE_INSTALL_PREFIX}/glog NO_DEFAULT_PATH REQUIRED)
    if(TARGET glog::glog)
        message(STATUS "glog installed successfully")
        remove_shared(glog::glog)
        string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
        get_target_property(gloglib  glog::glog IMPORTED_LOCATION_${BUILD_TYPE})
        target_link_libraries(glog::glog INTERFACE ${gloglib})

    else()
        message(STATUS "config_result: ${config_result}")
        message(STATUS "build_result: ${build_result}")
        message(FATAL_ERROR "glog could not be downloaded.")
    endif()

else()
    message(FATAL_ERROR "Dependency glog not found and DOWNLOAD_MISSING is OFF")
endif()