
function(remove_shared target_name)
    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    foreach(lib ${target_libs})
        if(NOT ${lib} MATCHES ".so")
            list(APPEND static_libs ${lib})
        endif()
    endforeach()
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${static_libs}")
endfunction()

function(remove_pthread target_name)
    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    foreach(lib ${target_libs})
        if(NOT ${lib} MATCHES "pthread")
            list(APPEND non_pthread_libs ${lib})
        endif()
    endforeach()
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${non_pthread_libs}")
endfunction()
