
function(remove_shared target_name)
    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    if(target_libs)
        foreach(lib ${target_libs})
            if(NOT ${lib} MATCHES ".so")
                list(APPEND static_libs ${lib})
            endif()
        endforeach()
    endif()
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${static_libs}")
endfunction()


function(remove_duplicates target_name)
    include(${PROJECT_SOURCE_DIR}/cmake-modules/getExpandedTarget.cmake)
    expand_target_libs(${target_name} target_libs)
    list(REMOVE_DUPLICATES target_libs)
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${target_libs}")
endfunction()

function(remove_pthread_shallow target_name)
#    include(${PROJECT_SOURCE_DIR}/cmake-modules/getExpandedTarget.cmake)
#    expand_target_libs(${target_name} target_libs)
    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    foreach(lib ${target_libs})
        if(NOT ${lib} MATCHES "thread|Thread")
            list(APPEND non_pthread_libs ${lib})
        endif()
    endforeach()
#    list(REMOVE_DUPLICATES non_pthread_libs)
#    remove_duplicates(non_pthread_libs)
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${non_pthread_libs}")
endfunction()

function(remove_pthread_recursive target_name)
    include(${PROJECT_SOURCE_DIR}/cmake-modules/getExpandedTarget.cmake)
    expand_target_libs(${target_name} target_libs)
    #    get_target_property(target_libs ${target_name} INTERFACE_LINK_LIBRARIES)
    foreach(lib ${target_libs})
        if(NOT ${lib} MATCHES "thread|Thread")
            list(APPEND non_pthread_libs ${lib})
        endif()
    endforeach()
    list(REMOVE_DUPLICATES non_pthread_libs)
    #    remove_duplicates(non_pthread_libs)
    set_target_properties(${target_name} PROPERTIES INTERFACE_LINK_LIBRARIES "${non_pthread_libs}")
endfunction()
