function(find_arpack_ng)

    if(DMRG_PACKAGE_MANAGER MATCHES "find|cmake")
        foreach (tgt BLAS::BLAS;LAPACK::LAPACK;gfortran::gfortran)
            if(NOT TARGET ${tgt})
                list(APPEND arpack_ng_MISSING_TARGET ${tgt})
                mark_as_advanced(arpack_ng_MISSING_TARGET)
            endif()
        endforeach()
        if(arpack_ng_MISSING_TARGET)
            message(FATAL_ERROR "arpack-ng: dependencies missing [${arpack_ng_MISSING_TARGET}]")
        endif()
    endif()

    find_package(arpack-ng 3.8.0 ${N5} ${N6} ${N7} ${N8} ${REQUIRED}) # Flags ignore system packages. See cmake/SetupPaths.cmake
    if(NOT arpack-ng_FOUND AND DMRG_PACKAGE_MANAGER MATCHES "cmake")
        message(STATUS "arpack-ng will be installed into ${DMRG_DEPS_INSTALL_DIR}/arpack-ng")
        include(cmake/InstallPackage.cmake)
        install_package(arpack-ng "${DMRG_DEPS_INSTALL_DIR}" "")
        find_package(arpack-ng 3.8.0 HINTS ${DMRG_DEPS_INSTALL_DIR} NO_DEFAULT_PATH REQUIRED)
    endif()

    if(arpack-ng_FOUND AND TARGET ARPACK::ARPACK)
        target_link_libraries(ARPACK::ARPACK INTERFACE BLAS::BLAS LAPACK::LAPACK gfortran::gfortran)
    else()
        message(FATAL_ERROR "arpack-ng not found")
    endif()
endfunction()

find_arpack_ng()