name: Ubuntu 20.04

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  ci:
    name: ${{ matrix.compiler }}-${{ matrix.linkage }}-${{ matrix.manager }}
    runs-on: ubuntu-20.04
    env:
      cache-name: cache-v1-${{ matrix.compiler }}-${{ matrix.linkage }}-${{ matrix.manager }}
    strategy:
      fail-fast: true # True stops all on first error. Stick to false when debugging
      matrix:
        include:
          - { compiler: gcc,   manager: cmake        , build_type: Debug   , linkage: static}
          - { compiler: gcc,   manager: cmake        , build_type: Debug   , linkage: shared}
          - { compiler: gcc,   manager: conan        , build_type: Release , linkage: static}
          - { compiler: gcc,   manager: conan        , build_type: Release , linkage: shared}
          - { compiler: clang, manager: cmake        , build_type: Debug   , linkage: static}
          - { compiler: clang, manager: cmake        , build_type: Debug   , linkage: shared}
          - { compiler: clang, manager: conan        , build_type: Release , linkage: static}
          - { compiler: clang, manager: conan        , build_type: Release , linkage: shared}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        if: contains(matrix.manager, 'conan')
        with:
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.conan/data
            ~/dmrg-deps-install
            ~/.ccache
          key: ${{ env.cache-name }}

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ env.cache-name }}
          max-size: 1000M


      - name: Setup gcc # compilers are already installed on the CI
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get install gcc-10 g++-10 gfortran -y
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "CC=gcc-10"   >> $GITHUB_ENV
          echo "CXX=g++-10"  >> $GITHUB_ENV

      - name: Setup clang
        if: matrix.compiler == 'clang' # compilers are already installed on the CI # sudo apt-get install libclang-10-dev gfortran -y
        run: |
          echo "FC=gfortran"     >> $GITHUB_ENV
          echo "CC=clang-10"     >> $GITHUB_ENV
          echo "CXX=clang++-10"  >> $GITHUB_ENV

      - name: Setup apt packages
        if: contains(matrix.manager,'find')
        run: sudo apt install libhdf5-dev libspdlog-dev libeigen3-dev gcovr ninja-build -y

      - name: Setup coverage
        if: contains(matrix.manager,'cmake')
        run: sudo apt install gcovr -y

      - name: Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Setup Python
        run: |
          pip install -r requirements.txt

      - name: Setup conan
        if: matrix.manager == 'conan'
        run: |
          pip install conan
          conan user

      - name: Setup OpenBLAS core type
        run: echo "OPENBLAS_CORETYPE=Haswell" >> $GITHUB_ENV

        # For conan: ceres-solver must be compiled in release mode because it only works with glog in release mode
      - name: Build
        run: python build.py  \
          --default-actions \
          --build-type=${{ matrix.build_type }} \
          --package-manager=${{ matrix.manager }} \
          --shared=${{ matrix.linkage == 'shared' }}

      - name: Test
        run: |
          cd build/${{ matrix.build_type }}
          ctest -C ${{ matrix.build_type }} --extra-verbose -R dmrg

      - name: Coverage
        if: matrix.compiler == 'gcc' && matrix.linkage == 'static' && matrix.manager == 'cmake'
        run: |
          # Create lcov report
          lcov --capture --directory build/Debug --output-file coverage.info
          lcov --remove coverage.info '*/dmrg-install*' '*/test-*' '/usr/*' '*include/fmt/*' '*include/spdlog/*' '*/Eigen/*' '*/hdf5/*' '*catch.hpp' --output-file coverage.info # filter system-files
          lcov --list coverage.info # debug info
          # Upload report to CodeCov
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"




